type: web
name: logistics-app-service
env: docker
plan: starter
region: fra
dockerfilePath: Dockerfile
envVars:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "10000"
  - key: DB_PATH
    value: /app/backend/data/logistics.db
disk:
  name: logistics-db
  mountPath: /app/backend/data
  sizeGB: 1